# Generated by Django 5.0.4 on 2024-04-14 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_cart_cartitems'),
    ]

    operations = [
        migrations.CreateModel(
            name='logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foo', models.TextField()),
                ('bar', models.FileField(blank=True, upload_to='logo-pictures')),
            ],
        ),
    ]
