# Generated by Django 5.0.4 on 2024-04-14 18:11

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logo',
            name='foo',
        ),
        migrations.RemoveField(
            model_name='logo',
            name='id',
        ),
        migrations.AddField(
            model_name='logo',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='logo',
            name='logos',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='logo',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='logo',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='logo',
            name='bar',
            field=models.ImageField(upload_to='logo-pictures'),
        ),
    ]
